### ISSUE TITLE
Odoo 15.0 version question

### ISSUE THREAD

**Issue by litnimax** [akretion/odoo-py3o-report-templates#7]
Hi!
I can see 16.0 branch but no 15.0.
Is 15.0 planned to be released?
Thanks.

**Comment by rvalyi** [comment]
I cannot speak for @alexis-via who is the main author, but it's very unlikely. Indeed at Akretion we tend to skip odd Odoo versions to have a stronger focus on even versions. We do migrate a few modules to Odoo versions occasionally to increase their adoption, but that's quite unlikely for such reports. We might do it if you pay for it, but it's again unlikely we have an offer/demand match on such reports for v15.

**Comment by litnimax** [comment]
Hi again!
Thanks for clearing this out.
Closing the ticket.
